---
Li-Ion:
  VoltageMax : 4.2
  VoltageMin : 2.8
  Capacity : null # null ends up like None in python
  CChargeMax : 0.7
  CChargeMin : 0.3
  CChargeCutOff : 0.05

  SOC_OCV:
    0 : 2.84
    10 : 3.26
    20 : 3.47
    30 : 3.55
    40 : 3.63
    50 : 3.68
    60 : 3.74
    70 : 3.85
    80 : 3.95
    90 : 4.06
    100 : 4.19

  SOC_CR:
    0: 0.4
    10 : 0.4
    20 : 0.4
    30 : 0.4
    40 : 0.5
    50 : 0.6
    60 : 0.6
    70 : 0.6
    80 : 0.6
    90 : 0.6
    100 : 0.6